spring:
  application:
    name: finances
  datasource:
    url: jdbc:postgresql://localhost:5432/finances
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect