spring:
  application:
    name: finances
  datasource:
    url: jdbc:postgresql://localhost:5432/finances
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format: